const state = { currentView:'dashboard', analysis:null, challengeId:null, prompts:[], theme:localStorage.getItem('rtcc-theme') || 'dark', folderPath:'', challenges:[], techniques:[], archive:null, selectedTechnique:null };
const titles = {
  dashboard:['Dashboard','Your red-team archive, analyzer, and prompt workspace.'],
  analyze:['New Challenge','Deep deterministic analysis of a competition objective.'],
  prompts:['Prompt Forge','Generate targeted prompt variants from the current analysis.'],
  archive:['Import Archive','Index nine months of folders without changing the originals.'],
  search:['History Search','Find related attacks, outcomes, and patterns from your archive.'],
  techniques:['Techniques','Your evolving attack taxonomy and historical performance.'],
  attempts:['Attempts','Log what you tried so the engine learns from outcomes.'],
  evidence:['Evidence','Trace screenshots and documents back to the originating competition.'],
  stats:['Statistics','See your red-team history as measurable patterns.'],
  settings:['Settings','Appearance and local archive defaults.']
};

document.documentElement.dataset.theme = state.theme;

function qs(s){return document.querySelector(s)}
function qsa(s){return [...document.querySelectorAll(s)]}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(n){return new Intl.NumberFormat().format(Number(n||0))}
function toast(msg){const el=qs('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2200)}
async function api(path, options={}){const res=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await res.json();if(!res.ok||data.ok===false)throw new Error(data.error||'Request failed');return data}
function setLoading(btn, active, label='Working...'){if(!btn)return; if(active){btn.dataset.old=btn.textContent;btn.textContent=label;btn.disabled=true}else{btn.textContent=btn.dataset.old||btn.textContent;btn.disabled=false}}

function switchView(name){
  state.currentView=name;qsa('.view').forEach(v=>v.classList.remove('active'));qs(`#view-${name}`).classList.add('active');
  qsa('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));
  qs('#page-title').textContent=titles[name][0];qs('#page-subtitle').textContent=titles[name][1];
  if(name==='dashboard')loadDashboard();if(name==='archive')loadArchive();if(name==='techniques')loadTechniques();if(name==='attempts')loadAttempts();if(name==='evidence')loadEvidence();if(name==='stats')loadStats();if(name==='settings')loadSettings();
  window.scrollTo({top:0,behavior:'smooth'});
}

qsa('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
qsa('[data-jump]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.jump)));

function setTheme(theme){state.theme=theme;document.documentElement.dataset.theme=theme;localStorage.setItem('rtcc-theme',theme)}
qs('#theme-cycle').addEventListener('click',()=>{const all=['light','dark','red'];setTheme(all[(all.indexOf(state.theme)+1)%all.length])});
qsa('[data-theme-choice]').forEach(b=>b.addEventListener('click',()=>{setTheme(b.dataset.themeChoice);toast(`${b.textContent} theme enabled`)}));

async function loadDashboard(){
  const r=await api('/api/dashboard');const d=r.data;
  const metrics=[['Artifacts',d.documents],['Competitions',d.competitions],['Challenges',d.challenges],['Attempts',d.attempts],['Success / partial',d.successes],['Evidence',d.evidence]];
  qs('#dashboard-metrics').innerHTML=metrics.map(([a,b])=>`<div class="metric"><span>${esc(a)}</span><strong>${fmt(b)}</strong></div>`).join('');
  qs('#recent-imports').innerHTML=d.recent_imports.length?d.recent_imports.map(x=>`<div class="list-row"><div><b>${esc(x.root_path)}</b><span>${fmt(x.files_added)} added · ${fmt(x.files_updated)} updated</span></div><div class="meta"><small>${esc(x.created_at)}</small>${x.errors?`<span class="danger">${x.errors} errors</span>`:''}</div></div>`).join(''):'<div class="empty-state"><b>No imports yet</b><span>Import your competition archive to begin.</span></div>';
  qs('#recent-challenges').innerHTML=d.latest_challenges.length?d.latest_challenges.map(x=>`<div class="list-row"><div><b>${esc(x.name)}</b><span>${esc(x.competition||'Unassigned')}</span></div><small>${esc(x.created_at)}</small></div>`).join(''):'<div class="empty-state"><b>No challenges yet</b><span>Run the analyzer on a competition objective.</span></div>';
}

qs('#analyze-btn').addEventListener('click',async()=>{
  const btn=qs('#analyze-btn');const text=qs('#challenge-text').value.trim();if(!text){toast('Paste the competition objective first');return}
  setLoading(btn,true,'Analyzing...');
  try{
    const r=await api('/api/analyze',{method:'POST',body:JSON.stringify({text,name:qs('#challenge-name').value||'Untitled challenge',competition:qs('#challenge-competition').value,save:true})});
    state.analysis=r.data;state.challengeId=r.challenge_id;renderAnalysis(r.data);populatePromptDirections(r.data);await generatePrompts(null);toast('Analysis complete · prompts generated');
  }catch(e){toast(e.message)}finally{setLoading(btn,false)}
});

function oldPromptDetails(item,label='Show old prompts'){
  const prompts=(item?.metadata?.payload_candidates||[]).filter(Boolean);
  if(!prompts.length)return '';
  return `<details class="old-prompts"><summary>${esc(label)} (${prompts.length})</summary><div class="old-prompt-list">${prompts.slice(0,12).map((p,i)=>`<div class="old-prompt"><div class="old-prompt-head"><span>#${i+1}</span><button class="secondary tiny" data-copy-old="${esc(p)}">Copy</button></div><pre>${esc(p)}</pre></div>`).join('')}</div></details>`
}
function bindOldPromptButtons(){qsa('[data-copy-old]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();navigator.clipboard.writeText(b.dataset.copyOld||'');toast('Old prompt copied')}))}
function renderHistoricalPromptPanel(matches=[]){const rows=[];matches.forEach(m=>(m.metadata?.payload_candidates||[]).forEach(p=>{if(p&&!rows.some(x=>x.prompt===p))rows.push({prompt:p,file:m.file_name,competition:m.competition,outcome:m.outcome,similarity:m.similarity})}));qs('#history-prompt-count').textContent=rows.length?`(${rows.length})`:'';qs('#history-prompt-list').innerHTML=rows.length?rows.slice(0,40).map((x,i)=>`<div class="old-prompt"><div class="old-prompt-head"><div><b>${esc(x.competition||'Archive')}</b><small>${esc(x.file)} · ${esc(x.outcome)} · ${esc(x.similarity)}%</small></div><button class="secondary tiny" data-copy-old="${esc(x.prompt)}">Copy</button></div><pre>${esc(x.prompt)}</pre></div>`).join(''):'<p class="muted">No high-confidence old prompts were recovered from the closest archive matches yet.</p>';bindOldPromptButtons()}
function renderAnalysis(a){
  const s=a.summary||{};const objectives=a.objectives||[];const constraints=a.constraints||[];const bounds=a.boundaries||[];const matches=a.historical_matches||[];const mechanics=a.mechanics||{};const exact=mechanics.exact_values||{};
  const success=(mechanics.success_conditions||[]).slice(0,5);const failures=(mechanics.failure_conditions||[]).slice(0,5);
  qs('#analysis-results').innerHTML=`
    <div class="analysis-card"><span class="eyebrow">PRIMARY OBJECTIVE</span><h3>${esc(s.primary_objective||'')}</h3><div class="pill-row"><span class="pill">Scenario: ${esc(mechanics.scenario||'general')}</span><span class="pill">Complexity ${esc(s.complexity)}/10</span><span class="pill">No external AI</span></div></div>
    <div class="analysis-card"><h3>What the room actually scores</h3><div class="mechanics-grid"><div><span class="muted">Agent</span><b>${esc(mechanics.agent||'Not explicitly named')}</b></div><div><span class="muted">Required tool/action</span><b>${esc((mechanics.required_tools||[]).join(', ')||'Not extracted')}</b></div><div><span class="muted">Forbidden tool/path</span><b>${esc((mechanics.forbidden_tools||[]).join(', ')||'None extracted')}</b></div><div><span class="muted">Target</span><b>${esc(mechanics.target_entity||'Not extracted')}</b></div></div><h3 style="margin-top:14px">Exact scored values</h3><div class="pill-row">${Object.keys(exact).length?Object.entries(exact).map(([k,v])=>`<span class="pill"><b>${esc(k)}</b> = ${esc(v)}</span>`).join(''):'<span class="muted">No exact tool values extracted.</span>'}</div>${success.length?`<h3 style="margin-top:14px">Success conditions</h3>${success.map(x=>`<p class="good">✓ ${esc(x)}</p>`).join('')}`:''}${failures.length?`<h3 style="margin-top:14px">Failure conditions</h3>${failures.map(x=>`<p class="danger">✕ ${esc(x)}</p>`).join('')}`:''}</div>
    <div class="analysis-card"><h3>Relevant control points</h3>${bounds.length?bounds.map(b=>`<div class="direction"><div class="direction-head"><h4>${esc(b.type)}</h4><span class="score">${b.evidence.length} signal${b.evidence.length===1?'':'s'}</span></div>${b.evidence.slice(0,2).map(x=>`<p>${esc(x)}</p>`).join('')}</div>`).join(''):'<p>No strong control point extracted.</p>'}<details class="raw-signals"><summary>Show raw constraints (${constraints.length})</summary>${constraints.map(x=>`<p>• ${esc(x)}</p>`).join('')}</details></div>
    <div class="analysis-card"><h3>Recommended attack directions</h3>${(a.directions||[]).map(d=>`<div class="direction"><div class="direction-head"><h4>${esc(d.label)}</h4><span class="score">${esc(d.score)}%</span></div><div class="bar"><i style="width:${Number(d.score)}%"></i></div><p>${esc(d.why)}</p>${(d.signals||[]).map(x=>`<p>• ${esc(x)}</p>`).join('')}<div class="direction-actions"><button class="secondary tiny" data-forge="${esc(d.id)}">Forge prompts</button></div></div>`).join('')}</div>
    <div class="analysis-card"><h3>Suggested test order</h3>${(a.next_moves||[]).map(m=>`<div class="direction"><div class="direction-head"><h4>#${esc(m.rank)} ${esc(m.label)}</h4><span class="score">${esc(m.score)}%</span></div><p><b>Test:</b> ${esc(m.test_focus)}</p><p><b>Watch:</b> ${esc(m.watch_for)}</p></div>`).join('')}</div>
    <div class="analysis-card"><h3>Closest historical cases</h3><p class="muted">Old prompt text is hidden unless you open it.</p>${matches.length?matches.map(m=>`<div class="search-card"><div class="search-head"><div><h3>${esc(m.file_name)}</h3><div class="path">${esc(m.competition||'')} · ${esc(m.path)}</div></div><span class="similarity">${esc(m.similarity)}%</span></div><p>${esc((m.excerpt||'').slice(0,420))}</p><div class="pill-row">${(m.techniques||[]).slice(0,5).map(t=>`<span class="pill">${esc(t)}</span>`).join('')}<span class="pill">${esc(m.outcome)}</span></div>${oldPromptDetails(m)}</div>`).join(''):'<p>Import your archive to enable historical matching.</p>'}</div>`;
  qsa('[data-forge]').forEach(b=>b.addEventListener('click',()=>{switchView('prompts');qs('#prompt-direction').value=b.dataset.forge;generatePrompts(b.dataset.forge)}));bindOldPromptButtons();renderHistoricalPromptPanel(matches)
}

function populatePromptDirections(a){const sel=qs('#prompt-direction');sel.innerHTML='<option value="">Auto-select direction</option>'+((a.directions||[]).map(d=>`<option value="${esc(d.id)}">${esc(d.label)} (${esc(d.score)}%)</option>`).join(''))}
qs('#generate-prompts').addEventListener('click',()=>generatePrompts(qs('#prompt-direction').value||null));
async function generatePrompts(direction){if(!state.analysis){toast('Analyze a challenge first');switchView('analyze');return}const btn=qs('#generate-prompts');setLoading(btn,true,'Generating...');try{const mode=qs('#prompt-mode')?.value||'standard';const count=Number(qs('#prompt-count')?.value||10);const r=await api('/api/prompts',{method:'POST',body:JSON.stringify({analysis:state.analysis,direction,count,mode})});state.prompts=r.data;renderPrompts(r.data)}catch(e){toast(e.message)}finally{setLoading(btn,false)}}
function renderPrompts(items){qs('#prompt-list').innerHTML=items.map((p,i)=>`<div class="prompt-card"><div><span class="eyebrow">${esc(p.direction_label)}</span><h3>${esc(p.title)}</h3></div><pre>${esc(p.prompt)}</pre><p>${esc(p.rationale)}</p><div class="prompt-actions"><button class="secondary tiny" data-copy-prompt="${i}">Copy</button><button class="primary tiny" data-log-prompt="${i}">Log attempt</button></div></div>`).join('');qsa('[data-copy-prompt]').forEach(b=>b.addEventListener('click',()=>{navigator.clipboard.writeText(state.prompts[+b.dataset.copyPrompt].prompt);toast('Prompt copied')}));qsa('[data-log-prompt]').forEach(b=>b.addEventListener('click',()=>{const p=state.prompts[+b.dataset.logPrompt];switchView('attempts');qs('#attempt-prompt').value=p.prompt;qs('#attempt-technique').value=p.direction;toast('Prompt loaded into attempt log')}))}

function archiveOutcomeBadges(o={}){return `<span class="archive-outcome success">${fmt(o.success||0)} success</span><span class="archive-outcome partial">${fmt(o.partial||0)} partial</span><span class="archive-outcome failure">${fmt(o.failure||0)} fail</span>`}
function renderArchiveNode(node,depth=0){
  const search=[node.name,node.path,...(node.top_techniques||[]),...(node.top_models||[])].join(' ').toLowerCase();
  const children=(node.children||[]).map(x=>renderArchiveNode(x,depth+1)).join('');
  const files=(node.files||[]).map(f=>{const fileSearch=[f.file_name,f.rel_path,f.competition,f.outcome,...(f.techniques||[]),...((f.metadata||{}).models||[])].join(' ').toLowerCase();return `<div class="archive-file" data-search="${esc(fileSearch)}"><div class="archive-file-main"><span class="file-icon">${f.ext==='.pdf'?'PDF':(f.tags||[]).includes('image')?'IMG':'FILE'}</span><div><b>${esc(f.file_name)}</b><small>${esc(f.rel_path)}</small></div></div><div class="archive-file-meta"><span class="pill">${esc(f.outcome)}</span>${(f.techniques||[]).slice(0,2).map(t=>`<span class="pill">${esc(t)}</span>`).join('')}<span class="muted">${fmt(Math.round((f.size||0)/1024))} KB</span></div></div>`}).join('');
  return `<details class="archive-node depth-${depth}" data-search="${esc(search)}" ${depth===0?'open':''}><summary><div class="archive-node-title"><span class="folder-icon">▸</span><div><b>${esc(node.name)}</b><small>${fmt(node.file_count)} files · ${fmt(node.folder_count)} folders · ${fmt(node.evidence)} evidence</small></div></div><div class="archive-node-meta">${archiveOutcomeBadges(node.outcomes)}${(node.top_techniques||[]).slice(0,3).map(t=>`<span class="pill">${esc(t)}</span>`).join('')}</div></summary><div class="archive-node-body">${children}${files}</div></details>`
}
function filterArchive(){const q=(qs('#archive-filter')?.value||'').trim().toLowerCase();const files=qsa('#archive-tree .archive-file');files.forEach(el=>{el.hidden=!!q&&!el.dataset.search.includes(q)});const nodes=qsa('#archive-tree .archive-node').reverse();nodes.forEach(el=>{const own=el.dataset.search.includes(q);const visibleDesc=[...el.querySelectorAll(':scope > .archive-node-body > .archive-file, :scope > .archive-node-body > .archive-node')].some(x=>!x.hidden);el.hidden=!!q&&!own&&!visibleDesc;if(q&&!el.hidden)el.open=true})}
async function loadArchive(){
  const [tree,docs]=await Promise.all([api('/api/archive/tree'),api('/api/documents?limit=100')]);state.archive=tree.data;const d=tree.data;const root=d.tree||{};
  qs('#archive-summary').innerHTML=[['Top-level groups',(d.groups||[]).length],['Indexed files',d.total_files],['Evidence',root.evidence||0],['Success',root.outcomes?.success||0],['Partial',root.outcomes?.partial||0],['Failure',root.outcomes?.failure||0]].map(([a,b])=>`<div class="metric"><span>${esc(a)}</span><strong>${fmt(b)}</strong></div>`).join('');
  qs('#archive-tree').innerHTML=(d.groups||[]).length?(d.groups||[]).map(x=>renderArchiveNode(x,0)).join(''):'<div class="empty-state"><b>No archive indexed</b><span>Import your root folder above.</span></div>';
  renderDocumentTable(docs.data);filterArchive();
}
function renderDocumentTable(d){qs('#document-table').innerHTML=d.length?`<table class="table"><thead><tr><th>File</th><th>Group</th><th>Outcome</th><th>Techniques</th><th>Size</th></tr></thead><tbody>${d.map(x=>`<tr><td><div class="truncate" title="${esc(x.path)}">${esc(x.file_name)}</div><small class="muted">${esc(x.rel_path)}</small></td><td>${esc(x.competition)}${x.metadata?.models?.length?`<br><small class="muted">${esc(x.metadata.models.slice(0,2).join(', '))}</small>`:''}</td><td>${esc(x.outcome)}${x.metadata?.likely_failure_reason?`<br><small class="muted">${esc(x.metadata.likely_failure_reason)}</small>`:''}</td><td>${(x.techniques||[]).slice(0,3).map(t=>`<span class="pill">${esc(t)}</span>`).join(' ')}</td><td>${fmt(Math.round((x.size||0)/1024))} KB</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state"><b>No artifacts indexed</b><span>Import your archive above.</span></div>'}
async function loadDocuments(){const r=await api('/api/documents?limit=100');renderDocumentTable(r.data)}
qs('#archive-filter').addEventListener('input',filterArchive);
qs('#import-btn').addEventListener('click',async()=>{const path=qs('#archive-path').value.trim();if(!path){toast('Choose an archive folder');return}const btn=qs('#import-btn');setLoading(btn,true,'Importing...');qs('#import-result').innerHTML='<div class="analysis-card"><b>Scanning folders and indexing artifacts...</b></div>';try{const r=await api('/api/import',{method:'POST',body:JSON.stringify({path})});const d=r.data;qs('#import-result').innerHTML=`<div class="metrics" style="margin-top:16px"><div class="metric"><span>Seen</span><strong>${fmt(d.files_seen)}</strong></div><div class="metric"><span>Added</span><strong>${fmt(d.files_added)}</strong></div><div class="metric"><span>Updated</span><strong>${fmt(d.files_updated)}</strong></div><div class="metric"><span>Duplicates</span><strong>${fmt(d.duplicates)}</strong></div><div class="metric"><span>Skipped</span><strong>${fmt(d.skipped)}</strong></div><div class="metric"><span>Errors</span><strong>${fmt(d.errors)}</strong></div></div>${d.error_samples?.length?`<div class="analysis-card"><h3>Import errors</h3>${d.error_samples.map(x=>`<p>${esc(x.file)} — ${esc(x.error)}</p>`).join('')}</div>`:''}`;await loadArchive();toast('Archive imported and organized')}catch(e){qs('#import-result').innerHTML=`<div class="analysis-card danger">${esc(e.message)}</div>`}finally{setLoading(btn,false)}});

qs('#search-btn').addEventListener('click',runSearch);qs('#search-query').addEventListener('keydown',e=>{if(e.key==='Enter')runSearch()});
async function runSearch(){const q=qs('#search-query').value.trim();if(!q)return;const r=await api('/api/search?q='+encodeURIComponent(q));const d=r.data;qs('#search-results').innerHTML=d.length?d.map(x=>`<div class="search-card"><div class="search-head"><div><h3>${esc(x.file_name)}</h3><div class="path">${esc(x.competition||'')} · ${esc(x.path)}</div></div><span class="similarity">${esc(x.similarity)}%</span></div><p>${esc((x.excerpt||'').slice(0,700))}</p>${x.metadata?.likely_success_mechanism?`<p class="good">${esc(x.metadata.likely_success_mechanism)}</p>`:''}${x.metadata?.likely_failure_reason?`<p class="warn">${esc(x.metadata.likely_failure_reason)}</p>`:''}<div class="pill-row">${(x.metadata?.models||[]).slice(0,3).map(t=>`<span class="pill">${esc(t)}</span>`).join('')}${(x.techniques||[]).map(t=>`<span class="pill">${esc(t)}</span>`).join('')}<span class="pill">${esc(x.outcome)}</span></div>${oldPromptDetails(x,'Show recovered prompts')}</div>`).join(''):'<div class="empty-state"><b>No close match</b><span>Try broader terms or import more archive material.</span></div>';bindOldPromptButtons()}

async function loadTechniques(){
  const r=await api('/api/techniques');state.techniques=r.data;
  qs('#technique-grid').innerHTML=r.data.map(t=>`<button class="technique-item ${state.selectedTechnique===t.id?'active':''}" data-technique="${esc(t.id)}"><div><h3>${esc(t.label)}</h3><p>${esc(t.why)}</p></div><div class="technique-item-stats"><span><b>${fmt(t.documents||0)}</b> hits</span><span><b>${t.success_rate==null?'—':esc(t.success_rate)+'%'}</b> success</span></div></button>`).join('');
  qsa('[data-technique]').forEach(b=>b.addEventListener('click',()=>loadTechniqueDetail(b.dataset.technique)));populateAttemptTechniques();
  if(state.selectedTechnique)loadTechniqueDetail(state.selectedTechnique,false)
}
async function loadTechniqueDetail(id,refreshList=true){
  state.selectedTechnique=id;if(refreshList)qsa('[data-technique]').forEach(x=>x.classList.toggle('active',x.dataset.technique===id));
  const meta=state.techniques.find(x=>x.id===id)||{id,label:id,why:''};qs('#technique-detail').innerHTML='<div class="empty-state"><b>Loading technique history...</b></div>';
  try{const r=await api('/api/technique/detail?id='+encodeURIComponent(id));const d=r.data;const rated=(d.outcomes?.success||0)+(d.outcomes?.partial||0)+(d.outcomes?.failure||0);qs('#technique-detail').innerHTML=`<div class="technique-detail-head"><span class="eyebrow">${esc(id)}</span><h2>${esc(meta.label)}</h2><p>${esc(meta.why)}</p><div class="technique-actions"><button class="secondary tiny" id="tech-search">Search this technique</button>${state.analysis&&state.analysis.directions?.some(x=>x.id===id)?'<button class="primary tiny" id="tech-forge">Forge for current challenge</button>':''}</div></div><div class="metrics technique-metrics">${[['Archive hits',d.documents.length],['Competitions',d.competitions.length],['Rated outcomes',rated],['Success rate',d.success_rate==null?'—':d.success_rate+'%']].map(([a,b])=>`<div class="metric"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('')}</div><h3 class="section-title">Where it appeared</h3><div class="tech-comp-list">${d.competitions.length?d.competitions.slice(0,30).map(c=>`<div class="tech-comp-row"><b>${esc(c.competition)}</b><span>${fmt(c.documents)} files</span><span class="good">${fmt(c.success)} success</span><span class="danger">${fmt(c.failure)} fail</span></div>`).join(''):'<p class="muted">No imported files currently tagged with this technique.</p>'}</div><h3 class="section-title">Archive evidence</h3><div class="tech-doc-list">${d.documents.length?d.documents.slice(0,100).map(x=>`<div class="tech-doc-row-wrap"><div class="tech-doc-row"><div><b>${esc(x.file_name)}</b><small>${esc(x.rel_path)} · ${esc(x.competition||'Unassigned')}</small></div><span class="pill">${esc(x.outcome)}</span></div>${oldPromptDetails(x,'Show prompts')}</div>`).join(''):'<p class="muted">No matching archive files yet.</p>'}</div>${d.attempts.length?`<h3 class="section-title">Logged attempts</h3><div class="tech-doc-list">${d.attempts.map(x=>`<div class="tech-doc-row"><div><b>${esc(x.challenge_name||'Unlinked attempt')}</b><small>${esc(x.notes||x.prompt||'')}</small></div><span class="pill">${esc(x.outcome)}</span></div>`).join('')}</div>`:''}`;
    bindOldPromptButtons();qs('#tech-search')?.addEventListener('click',()=>{switchView('search');qs('#search-query').value=meta.label;runSearch()});qs('#tech-forge')?.addEventListener('click',()=>{switchView('prompts');qs('#prompt-direction').value=id;generatePrompts(id)})
  }catch(e){qs('#technique-detail').innerHTML=`<div class="analysis-card danger">${esc(e.message)}</div>`}
}
function populateAttemptTechniques(){if(!state.techniques.length)return;qs('#attempt-technique').innerHTML='<option value="">Unspecified</option>'+state.techniques.map(t=>`<option value="${esc(t.id)}">${esc(t.label)}</option>`).join('')}

async function loadAttempts(){if(!state.techniques.length)await loadTechniques();const [c,a]=await Promise.all([api('/api/challenges'),api('/api/attempts')]);state.challenges=c.data;qs('#attempt-challenge').innerHTML='<option value="">Unlinked</option>'+c.data.map(x=>`<option value="${x.id}">${esc(x.name)}${x.competition?' · '+esc(x.competition):''}</option>`).join('');qs('#attempt-list').innerHTML=a.data.length?a.data.map(x=>`<div class="list-row"><div><b>${esc(x.challenge_name||'Unlinked attempt')}</b><span>${esc(x.technique||'Unspecified')} · ${esc(x.outcome)}</span></div><small>${esc(x.created_at)}</small></div>`).join(''):'<div class="empty-state"><b>No attempts logged</b><span>Save prompts and outcomes here.</span></div>'}
qs('#save-attempt').addEventListener('click',async()=>{const sel=qs('#attempt-challenge');const option=sel.options[sel.selectedIndex];const payload={challenge_id:sel.value?Number(sel.value):null,challenge_name:option&&sel.value?option.textContent.split(' · ')[0]:'',competition:option&&option.textContent.includes(' · ')?option.textContent.split(' · ').slice(1).join(' · '):'',prompt:qs('#attempt-prompt').value,response:qs('#attempt-response').value,outcome:qs('#attempt-outcome').value,technique:qs('#attempt-technique').value,notes:qs('#attempt-notes').value};await api('/api/attempts',{method:'POST',body:JSON.stringify(payload)});toast('Attempt saved');qs('#attempt-response').value='';qs('#attempt-notes').value='';loadAttempts()});

async function loadEvidence(){const r=await api('/api/evidence');qs('#evidence-grid').innerHTML=r.data.length?r.data.map(x=>`<div class="mini-card"><span class="eyebrow">${esc(x.ext.replace('.','').toUpperCase())}</span><h3>${esc(x.file_name)}</h3><p>${esc(x.competition||'Unassigned')}</p><p class="path">${esc(x.path)}</p><div class="pill-row">${(x.tags||[]).map(t=>`<span class="pill">${esc(t)}</span>`).join('')}</div></div>`).join(''):'<div class="empty-state"><b>No evidence indexed</b><span>Images and PDFs from imported folders will appear here.</span></div>'}

async function loadStats(){const r=await api('/api/stats');const d=r.data;const o=d.outcomes||{};qs('#stats-metrics').innerHTML=[['Success',o.success],['Partial',o.partial],['Failure',o.failure],['Unknown',o.unknown],['Techniques',d.techniques.length],['Competitions',d.competitions.length]].map(([a,b])=>`<div class="metric"><span>${esc(a)}</span><strong>${fmt(b)}</strong></div>`).join('');qs('#stats-techniques').innerHTML=d.techniques.slice(0,15).map(t=>`<div class="stat-row"><div class="line"><b>${esc(t.technique)}</b><span>${t.success_rate==null?'No rated attempts':esc(t.success_rate)+'%'}</span></div><div class="bar"><i style="width:${t.success_rate==null?0:t.success_rate}%"></i></div></div>`).join('')||'<div class="empty-state"><b>No technique data yet</b></div>';const max=Math.max(1,...d.competitions.map(x=>x.documents));qs('#stats-competitions').innerHTML=d.competitions.slice(0,20).map(c=>`<div class="stat-row"><div class="line"><b>${esc(c.competition)}</b><span>${fmt(c.documents)} files</span></div><div class="bar"><i style="width:${(c.documents/max)*100}%"></i></div></div>`).join('')||'<div class="empty-state"><b>No competition data yet</b></div>'}

async function loadSettings(){const r=await api('/api/settings');qs('#settings-archive').value=r.data.archive_root||'';if(!qs('#archive-path').value)qs('#archive-path').value=r.data.archive_root||''}
qs('#save-settings').addEventListener('click',async()=>{await api('/api/settings',{method:'POST',body:JSON.stringify({archive_root:qs('#settings-archive').value.trim()})});toast('Settings saved')});

async function browseFolder(path=''){const r=await api('/api/fs'+(path?'?path='+encodeURIComponent(path):''));const d=r.data;state.folderPath=d.path;qs('#folder-current').textContent=d.path||'Available drives';qs('#folder-up').dataset.path=d.parent||'';qs('#folder-select').disabled=!d.path;qs('#folder-list').innerHTML=d.folders.length?d.folders.map(x=>`<button class="folder-item" data-folder-path="${esc(x.path)}">📁 ${esc(x.name)}</button>`).join(''):'<div class="empty-state"><b>No subfolders</b><span>You can select the current folder.</span></div>';qsa('[data-folder-path]').forEach(b=>b.addEventListener('click',()=>browseFolder(b.dataset.folderPath)))}
qs('#browse-folder').addEventListener('click',async()=>{qs('#folder-modal').classList.add('open');await browseFolder(qs('#archive-path').value.trim())});qs('#folder-close').addEventListener('click',()=>qs('#folder-modal').classList.remove('open'));qs('#folder-up').addEventListener('click',()=>browseFolder(qs('#folder-up').dataset.path));qs('#folder-select').addEventListener('click',()=>{qs('#archive-path').value=state.folderPath;qs('#folder-modal').classList.remove('open')});

(async()=>{try{await loadDashboard();const s=await api('/api/settings');qs('#archive-path').value=s.data.archive_root||''}catch(e){toast('Could not connect to local engine')}})();